name: Docker Python

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */1 * * *"
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Build Docker
      #   run: docker build -t bro .

      - name: Run Docker
        env:
          TOKEN: ${{ secrets.TOKEN }}
        timeout-minutes: 59
        continue-on-error: true
        run: docker run --rm traffmonetizer/cli_v2 start accept --token $TOKEN

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: "*.png"
